### ISSUE TITLE
Settings always get reset

### ISSUE THREAD

**Issue by MathijsG** [Koenvh1/ets2-local-radio#12]
Everytime I install an update I always need to specify the ETS2 folder and setup the keys again. Can't this be in a config file which doesn't get overwritten or maybe get the ETS2 location from the registry or something? :-)

**Comment by Koenvh1** [comment]
I already started working on this, but it isn't finished yet... It'll probably be included in the next version.

**Comment by Koenvh1** [comment]
Should be fixed with https://github.com/Koenvh1/ets2-local-radio/commit/a7921688e3994ecfa7c91058cd4c34a2462ec8f3
If you want to try it: 
[ETS2 Local Radio server.zip](https://github.com/Koenvh1/ets2-local-radio/files/793909/ETS2.Local.Radio.server.zip)
Your settings will be reset again, but it will be the last time as the settings are now written to `settings.json`

**Comment by Koenvh1** [comment]
Included in 1.9.0
