### ISSUE TITLE
Problem after changing controller

### ISSUE THREAD

**Issue by bazzigoplay297** [Koenvh1/ets2-local-radio#193]
Hi!
I have a problem with the mod. I played with ETS2 and Local Radio fine for almost a year with my Dualshock 4, but in the end the controller broke, so I was forced to change it to a brand new Xbox One controller.
But, even if I changed the settings on the program, the mod in game isn't working anymore, it works only on the program menu.

Tried to unistall and reinstall ETS2 Local Radio, rebooting, and nothing changed. What to do?

EDIT: BTW with the keyboard is still working also in game, so seems like something is blocking the Xbox One Controller in game to operate on the Local Radio app

If it can help here is my error log
[Error log ets2.txt](https://github.com/Koenvh1/ets2-local-radio/files/10146142/Error.log.ets2.txt)

**Comment by Koenvh1** [comment]
Fairly certain this is related to this: https://stackoverflow.com/questions/48748313/using-directinput-with-xbox-one-controller-and-window-focus-on-windows-10

Basically Local Radio uses DirectInput to detect whether you have pressed any buttons, and the Xbox One controller drivers don't tell whether any buttons have been pressed unless the window is in the foreground (which it isn't, since you are playing ETS2). Not sure how to solve it.

**Comment by bazzigoplay297** [comment]
> Fairly certain this is related to this: https://stackoverflow.com/questions/48748313/using-directinput-with-xbox-one-controller-and-window-focus-on-windows-10
> 
> Basically Local Radio uses DirectInput to detect whether you have pressed any buttons, and the Xbox One controller drivers don't tell whether any buttons have been pressed unless the window is in the foreground (which it isn't, since you are playing ETS2). Not sure how to solve it.

Oh well, thank you anyway, I'll continue to use the keyboard for this beautiful app
