### ISSUE TITLE
Simulator not running 

### ISSUE THREAD

**Issue by skipper00123** [Koenvh1/ets2-local-radio#5]
I can't get pass this problem ,,  

" Please make sure the plugin is installed and working..."   what plugin you mean ?? the telemetry one in the plugins folder ??  plus  i couldn't install vc++ 2015 ? is it necessary for the mod to work? i have windows 7 32bit  does vc++2015 requires Service pack one to be installed ?  please help, i really want to try out this mod !

**Comment by Koenvh1** [comment]
Do you mean that ETS2 Local Radio shows that the simulator (ETS2/ATS) is not running, while it actually is? Because yes, that probably has to do with the Visual C++ redistributable. 

You can check that by opening the `game.log.txt` in the My Documents\Euro Truck Simulator 2 or My Documents\American Truck Simulator folder. It should contain a line saying: 
```
loading 'ets2-telemetry' 'X:/Path/Euro Truck Simulator 2/bin/win_x86/plugins/ets2-telemetry.dll'
```
And under that:
```
00:00:20.006 : <ERROR> [sdk] prism::sdk::lookup_channel: channel 'truck.adblue.consumption.average' not found
00:00:20.006 : <ERROR> [sdk] prism::sdk::lookup_channel: SCS_U32_NIL is not valid parameter for array channel 'truck.hshifter.select'
00:00:20.006 : <ERROR> [sdk] prism::sdk::telemetry_register_for_channel: channel 'truck.electric.enabled' index 4294967295 has already callback for type 1
00:00:20.006 : <ERROR> [sdk] prism::sdk::telemetry_register_for_channel: type 1 is not supported by channel 'truck.light.aux.front' index 4294967295
00:00:20.006 : <ERROR> [sdk] prism::sdk::telemetry_register_for_channel: type 1 is not supported by channel 'truck.light.aux.roof' index 4294967295
00:00:20.006 : <ERROR> [sdk] prism::sdk::lookup_channel: channel 'truck.adblue.consumption.average' not found
```
If the error is different, it may very well be a redistributable issue. If so, please install it. I am not sure whether it requires SP1 to be installed, but it may very well do. If so, you can find that here: https://www.microsoft.com/en-us/download/details.aspx?id=5842 (I'd recommend installing it anyway, as Windows 7 without service pack is no longer supported by Microsoft)

If the first line does not show up, then you may need to copy the plugin manually to your ETS2 installation folder. It can be found in the plugin folder under ETS2 Local Radio, and the folder structure is the same as the installation folder for Euro Truck Simulator 2.

Hope that solves your issue, if not, please let me know.

**Comment by skipper00123** [comment]
I have this in the game log :

00:00:18.261 : loading 'ets2-telemetry' 'E:/Euro Truck Simulator 2/bin/win_x86/plugins/ets2-telemetry.dll'
00:00:18.262 : <ERROR> unable to load: 0000007E
i don't have the other lines you wrote ,, plus i found out that C++ 2015 needs windows 7 sp 1 to be installed ,, i am currently working on downloading and installing it !!

**Comment by skipper00123** [comment]
I have installed sp1 , and the C++2015 but i still get simulator is not yet running :(

**Comment by Koenvh1** [comment]
Hmm... Does the log show the same error after you reboot the computer and restart ETS2? If so, I will have to ask @nlhans whether he knows a solution, as he is the creator of the plugin.

**Comment by skipper00123** [comment]
i reinstalled windows 7 , installed sp 1 again, installed C++ 2015 and c++ 2010 since i read that this error ( 00:00:18.262 : unable to load: 0000007E) can be fixed by installing c++2010!! still the same thing !! i get in the software in red :" simulator not yet running" and in log file the same error after the line that says loading plugin  (  00:00:18.262 : unable to load: 0000007E)   :'( i give up !!

**Comment by konrad1520** [comment]
Try to install all of C++ also for 64bit system for me it works know :) !

**Comment by blargle-ragequit** [comment]
I'm getting the 0000007E as well now.  I've installed the C++ redistributable for both 32 and 64 bit, and I've followed all the troubleshooting on the main page.

**Comment by Koenvh1** [comment]
Well, you miss _some_ dependency, probably the C++ runtime. Did you install both the 64-bit and 32-bit version? You can also try this one:
https://www.microsoft.com/en-us/download/details.aspx?id=8328
https://www.microsoft.com/en-us/download/details.aspx?id=13523

**Comment by blargle-ragequit** [comment]
Already had C++ runtime both 2010 and 2015 each for both x86 and x64.  Reinstalled/repaired both.  Problem persists.

**Comment by Koenvh1** [comment]
I'll ask @nlhans , the author of the plugin, whether he knows a way to solve it.

**Comment by nlhans** [comment]
I honestly don't know, as I haven't encountered this issue myself.
Perhaps the 2012 runtimes are missing? Because the project is built with Visual Studio 2012

**Comment by blargle-ragequit** [comment]
I installed the x86 and x64 C++ 2012 runtimes and now the issue is fixed.

**Comment by Koenvh1** [comment]
I uploaded an alternative ets2-telemetry.dll, which should solve this issue.
