### ISSUE TITLE
Romania Extended & YKSRSK Support

### ISSUE THREAD

**Issue by Qrusher14242** [Koenvh1/ets2-local-radio#73]
Last time i tried this with Romania Extended, i don't believe it worked. Any plans for that? Romania Extended's author has also rescaled YKS Turkey to 1:19 scale(at http://www.roextended.ro) . Will that mess with Turkey support?
Also would like to voice my support for EAA, a wonderful map and would be cool to have radio on it. Love your app!

**Comment by Koenvh1** [comment]
If you could provide the cities and stations, then sure, I will add them. For getting the cities, see https://github.com/Koenvh1/ETS2-City-Coordinate-Retriever/blob/master/README.md, for the stations, see the custom stations example file for the format.

That'll be doable for Romania Extended and YKS Turkey, as the stations are for the most part already included anyway, but it'll be a bit more difficult for EAA, due to radio stations being based per city instead of per country.

**Comment by Qrusher14242** [comment]
Here are the coordinates for Romania Extended 2.1 and YKSRSK 1.6 (the rescaled YKS Turkey map)
[Coordinates.zip](https://github.com/Koenvh1/ets2-local-radio/files/2959461/Coordinates.zip). EAA seems like it could take days to get those coordinates with all those cities lol But ill see about doing it.

**Comment by Koenvh1** [comment]
I hope to look at it this weekend or the next
